services:
  - type: web
    name: licencias-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TZ
        value: America/Santo_Domingo
    buildCommand: ""
    startCommand: ""
